resources:
- ../base/
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: "ingress-nginx-controller"
    spec:
      replicas: 3
